[build]
  command = "npm install && npm run build && cp _headers dist/spa/ && cp _redirects dist/spa/"
  publish = "dist/spa"
  environment = { NODE_VERSION = "18" }

[build.environment]
  NODE_VERSION = "20.12.2" # Puedes cambiar seg√∫n lo que uses localmente

[functions]
  directory = "netlify/functions"

[functions."*"]
  external_node_modules = [
    "express",
    "mongoose",
    "bcryptjs",
    "jsonwebtoken",
    "passport",
    "passport-google-oauth20"
  ]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = { Role = ["path"], headers = { accept = "text/html" } }
